In [1]:
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_percentage_error

# Showing values upto 2 decimal places
pd.set_option('display.float_format', '{:.3f}'.format)

path = '/Users/umeshnagar/deskto/All Project/all_py_project/all_projects/normal_programs/Zelestra_Assessment/Assessment 2/'
# Load datasets
train_df = pd.read_csv(path + "train.csv", parse_dates=["timestamp"])
test_df = pd.read_csv(path + "test.csv", parse_dates=["timestamp"])

train_df['target'] = np.where(train_df['energy_output'] < 0, 1, train_df['energy_output'])
test_df['target'] = np.where(test_df['energy_output'] < 0, 1, test_df['energy_output'])

In [2]:
train_df.head()

,timestamp,energy_output,irradiance_global_index,irradiance_global_reference,irradiance_horizontal,module_temperature_1,module_temperature_2,module_temperature_3,wind_direction,relative_humidity,...,incident_radiation_2,incident_radiation_4,incident_radiation_3,reflected_radiation_1,reflected_radiation_2,reflected_radiation_4,reflected_radiation_3,ambient_temperature,wind_speed,target
0,2024-10-01 00:00:00,0.000,0.000,0.000,0.000,22.144,21.766,21.888,166.494,99.997,...,NaN,0.000,NaN,0.000,NaN,0.000,NaN,23.450,0.000,0.000
1,2024-10-01 01:00:00,0.000,0.000,0.000,0.000,21.904,21.492,21.647,257.272,99.996,...,NaN,0.000,NaN,0.000,NaN,0.000,NaN,23.215,0.000,0.000
2,2024-10-01 02:00:00,0.000,0.000,0.000,0.000,22.539,22.290,22.320,212.567,99.997,...,NaN,0.000,NaN,0.000,NaN,0.000,NaN,23.301,0.000,0.000
3,2024-10-01 03:00:00,0.000,0.000,0.000,0.000,22.686,22.513,22.485,157.928,99.996,...,NaN,0.000,NaN,0.000,NaN,0.000,NaN,23.353,1.833,0.000
4,2024-10-01 04:00:00,0.000,0.000,0.000,0.000,23.158,22.859,22.862,142.271,99.997,...,NaN,0.000,NaN,0.000,NaN,0.000,NaN,23.506,0.000,0.000

In [4]:
def filter_specific_hours(train_df, test_df):
    train_df = train_df[train_df['timestamp'].dt.hour.isin([6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17])]

    test_df = test_df[test_df['timestamp'].dt.hour.isin([6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17])]
    return train_df, test_df
    
train_df, test_df = filter_specific_hours(train_df, test_df)

In [5]:
def add_cyclic_feature(df):
    df['hour'] = df['timestamp'].dt.hour  

    # Apply sine and cosine transformations
    df['hour_sin'] = np.sin(2 * np.pi * df['hour'] / 24)
    df['hour_cos'] = np.cos(2 * np.pi * df['hour'] / 24)
    
    return df

train_df = add_cyclic_feature(train_df)
test_df = add_cyclic_feature(test_df)

In [6]:
test_df.head()

,timestamp,energy_output,irradiance_global_index,irradiance_global_reference,irradiance_horizontal,module_temperature_1,module_temperature_2,module_temperature_3,wind_direction,relative_humidity,...,reflected_radiation_1,reflected_radiation_2,reflected_radiation_4,reflected_radiation_3,ambient_temperature,wind_speed,target,hour,hour_sin,hour_cos
6,2025-01-01 06:00:00,2038.000,46.441,4.700,41.331,23.837,23.884,23.783,329.677,99.996,...,4.583,2.013,4.273,3.300,24.030,0.000,2038.000,6,1.000,0.000
7,2025-01-01 07:00:00,12751.000,196.127,17.815,102.575,26.821,29.517,-76.109,233.294,99.997,...,16.874,10.984,17.000,7.756,25.504,0.000,12751.000,7,0.966,-0.259
8,2025-01-01 08:00:00,18110.000,283.825,33.097,243.647,33.090,32.782,-172.837,160.793,98.223,...,30.168,27.739,25.797,26.414,26.706,1.651,18110.000,8,0.866,-0.500
9,2025-01-01 09:00:00,56705.000,885.500,52.974,595.486,46.941,48.600,-153.241,172.256,92.669,...,42.992,40.982,46.120,37.132,27.655,3.423,56705.000,9,0.707,-0.707
10,2025-01-01 10:00:00,57145.000,905.395,49.353,707.762,48.304,49.505,24.935,159.512,88.131,...,35.134,35.824,40.295,36.455,28.713,3.317,57145.000,10,0.500,-0.866

In [7]:
def add_lag_features(df):
    # Creating Target Variables (1 to 6-hour ahead)
    for h in range(1, 7):  
        df[f'target_{h}'] = df["energy_output"].shift(h)

    # Drop NaN values caused by shifting
    df.dropna(inplace=True)
    df.drop('hour',axis = 1,inplace=True)
    return df

train_df = add_lag_features(train_df)

In [8]:
train_df.head()

,timestamp,energy_output,irradiance_global_index,irradiance_global_reference,irradiance_horizontal,module_temperature_1,module_temperature_2,module_temperature_3,wind_direction,relative_humidity,...,wind_speed,target,hour_sin,hour_cos,target_1,target_2,target_3,target_4,target_5,target_6
830,2024-11-04 16:00:00,11244.000,162.456,20.711,134.267,34.580,34.464,34.103,132.226,82.827,...,2.497,11244.000,-0.866,-0.500,51366.000,62059.000,54025.000,47719.000,35348.000,20918.000
870,2024-11-06 08:00:00,48033.000,677.282,43.596,503.007,48.114,43.218,41.252,181.387,95.225,...,3.567,48033.000,0.866,-0.500,37260.000,6825.000,379.000,6755.000,29114.000,46021.000
877,2024-11-06 15:00:00,6675.000,100.834,11.785,82.600,29.844,29.785,29.756,162.538,86.727,...,3.247,6675.000,-0.707,-0.707,53954.000,38172.000,54366.000,58593.000,55180.000,54721.000
878,2024-11-06 16:00:00,12553.000,171.664,12.244,106.155,31.695,30.479,30.945,221.318,97.757,...,2.181,12553.000,-0.866,-0.500,6675.000,53954.000,38172.000,54366.000,58593.000,55180.000
1015,2024-11-12 09:00:00,38760.000,452.798,35.917,399.038,39.662,38.275,38.249,120.790,91.366,...,3.201,38760.000,0.707,-0.707,60171.000,18852.000,5193.000,1202.000,16746.000,33070.000

In [9]:
def prepare_input(train_df, test_df):
    train_df = train_df.fillna(train_df.mean())
    test_df = test_df.fillna(test_df.mean())

    # Select Features (Exclude target variables)
    features = [col for col in train_df.columns if col not in ["timestamp", "energy_output"] + [f'target_{h}' for h in range(1, 7)]]

    # Prepare input variables
    X_train = train_df[features]
    X_test_eval = test_df[features]  # Use test set only for evaluation
    
     # Standardize features (not mandatory for xgboost)
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test_eval = scaler.transform(X_test_eval)
    
    return X_train, X_test_eval

X_train,  X_test_eval = prepare_input(train_df, test_df)

In [10]:
# test_df.describe()

In [11]:
# Dictionary to store models & predictions
def prepar_output(df):
    models = {}
    predictions = pd.DataFrame({"timestamp": df["timestamp"], "month": df["timestamp"].dt.strftime("%Y-%m")})
    return predictions, models

predictions, models = prepar_output(test_df)

In [12]:
predictions.head()

             timestamp    month
6  2025-01-01 06:00:00  2025-01
7  2025-01-01 07:00:00  2025-01
8  2025-01-01 08:00:00  2025-01
9  2025-01-01 09:00:00  2025-01
10 2025-01-01 10:00:00  2025-01

In [13]:
def training_model(train_df, test_df):
    # Train separate models for each hour ahead
    for h in range(1, 7):
        y_train = train_df[f'target_{h}']

        # Train XGBoost model for h-hour ahead forecast
        model = xgb.XGBRegressor(objective='reg:squarederror', n_estimators=100, learning_rate=0.1, max_depth=6, random_state=42)
        model.fit(X_train, y_train)

        # Store model
        models[h] = model

        # Predict for test set
        predictions[f"{h}_hour_ahead"] = model.predict(X_test_eval)


    return predictions, test_df

predictions, test_df = training_model(train_df, test_df)

In [14]:
predictions.head()

,timestamp,month,1_hour_ahead,2_hour_ahead,3_hour_ahead,4_hour_ahead,5_hour_ahead,6_hour_ahead
6,2025-01-01 06:00:00,2025-01,12311.596,29977.551,42801.156,39525.418,39147.652,8824.229
7,2025-01-01 07:00:00,2025-01,6832.488,45976.398,38167.391,1348.388,55207.980,45424.492
8,2025-01-01 08:00:00,2025-01,27160.281,51422.570,39536.656,1348.388,23943.383,29320.312
9,2025-01-01 09:00:00,2025-01,48577.961,5875.111,470.523,14897.280,29115.215,40442.859
10,2025-01-01 10:00:00,2025-01,48577.961,5875.111,470.523,14897.280,29115.215,33589.082

In [15]:
def get_hourly_MAPE(test_df, predictions):
    # Compute MAPE for each forecast horizon
    for h in range(1, 7):
        predictions[f"MAPE_{h}_hour_ahead"] = mean_absolute_percentage_error(test_df["energy_output"].fillna(1), predictions[f"{h}_hour_ahead"])
    return predictions
predictions = get_hourly_MAPE(test_df, predictions)

In [16]:
predictions.head()

,timestamp,month,1_hour_ahead,2_hour_ahead,3_hour_ahead,4_hour_ahead,5_hour_ahead,6_hour_ahead,MAPE_1_hour_ahead,MAPE_2_hour_ahead,MAPE_3_hour_ahead,MAPE_4_hour_ahead,MAPE_5_hour_ahead,MAPE_6_hour_ahead
6,2025-01-01 06:00:00,2025-01,12311.596,29977.551,42801.156,39525.418,39147.652,8824.229,2.244,2.849,3.904,3.652,2.051,1.198
7,2025-01-01 07:00:00,2025-01,6832.488,45976.398,38167.391,1348.388,55207.980,45424.492,2.244,2.849,3.904,3.652,2.051,1.198
8,2025-01-01 08:00:00,2025-01,27160.281,51422.570,39536.656,1348.388,23943.383,29320.312,2.244,2.849,3.904,3.652,2.051,1.198
9,2025-01-01 09:00:00,2025-01,48577.961,5875.111,470.523,14897.280,29115.215,40442.859,2.244,2.849,3.904,3.652,2.051,1.198
10,2025-01-01 10:00:00,2025-01,48577.961,5875.111,470.523,14897.280,29115.215,33589.082,2.244,2.849,3.904,3.652,2.051,1.198

In [23]:
def get_monthly_mape(predictions):
    # Calculate Monthly Average MAPE (expanded format)
    
    for h in range(1, 7):
        predictions[f"MAPE_{h}_hour_ahead"]  = 100abs(test_df["energy_output"].fillna(1) - predictions[f"{h}_hour_ahead"]) / test_df["energy_output"].fillna(1)

    monthly_mape = predictions.groupby("month")[[f"MAPE_{h}_hour_ahead" for h in range(1, 7)]].mean()
    return monthly_mape

monthly_mape = get_monthly_mape(predictions)

In [24]:
monthly_mape.head()

,MAPE_1_hour_ahead,MAPE_2_hour_ahead,MAPE_3_hour_ahead,MAPE_4_hour_ahead,MAPE_5_hour_ahead,MAPE_6_hour_ahead
month,,,,,,
2025-01,240.432,299.244,410.265,382.659,228.424,132.181
2025-02,204.857,267.219,366.561,344.184,177.572,104.285

In [25]:
# Save results
# predictions.to_csv("multi_step_forecast.csv", index=False)
# monthly_mape.to_csv("monthly_mape_results.csv", index=True)

In [26]:
predictions.head()

,timestamp,month,1_hour_ahead,2_hour_ahead,3_hour_ahead,4_hour_ahead,5_hour_ahead,6_hour_ahead,MAPE_1_hour_ahead,MAPE_2_hour_ahead,MAPE_3_hour_ahead,MAPE_4_hour_ahead,MAPE_5_hour_ahead,MAPE_6_hour_ahead
6,2025-01-01 06:00:00,2025-01,12311.596,29977.551,42801.156,39525.418,39147.652,8824.229,504.102,1370.930,2000.155,1839.422,1820.886,332.985
7,2025-01-01 07:00:00,2025-01,6832.488,45976.398,38167.391,1348.388,55207.980,45424.492,46.416,260.571,199.329,89.425,332.970,256.243
8,2025-01-01 08:00:00,2025-01,27160.281,51422.570,39536.656,1348.388,23943.383,29320.312,49.974,183.946,118.314,92.554,32.211,61.901
9,2025-01-01 09:00:00,2025-01,48577.961,5875.111,470.523,14897.280,29115.215,40442.859,14.332,89.639,99.170,73.728,48.655,28.678
10,2025-01-01 10:00:00,2025-01,48577.961,5875.111,470.523,14897.280,29115.215,33589.082,14.992,89.719,99.177,73.931,49.050,41.221